version: '3.4'

services:
  database:
    image: postgres:alpine
    container_name: todo-backend-postgres
    restart: always
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - ./.data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: todo-backend-redis
    ports:
      - 6379:6379