server:
  schema: "https"
  domain: "todo.lan:9991"
  host: "0.0.0.0"
  port: 9991
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: ""
  dbname: "todo"
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
jwt:
  accessSecret: ""
  refreshSecret: ""
  accessTTL: 1000h
  refreshTTL: 4320h # 6 month
smtp:
  host: ""
  port: 465
  from: "TODO"
  username: ""
  password: ""
